[package]
name = "simple"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
rand = { workspace = true }

[features]
default = [ "slow_tests", "graph_sorted_nodes" ]

# Also run slow tests?
# Disable this feature when running with miri as its overhead
# is too high for some tests (tests take forever)
# i.e., cargo miri test doubly_linked_list --no-default-features
slow_tests = []

# Do _not_ even out work/chunks assigned to workers. Just send them raw.
# This imbalance can mean some workers can starve while others are overloaded.
par_letters_raw_chunks = []

# Use custom impl of mpmc channel instead of nightly mpmc
par_letters_my_mpmc = []

# Buffer writes by xorcism::writer()
xorcism_buffered_write = []

# For graph.rs, make output {:?} deterministic/sorted instead of random node ordering.
# Disable this for faster performance at the cost of non-determistic {:?} output.
# NB: Disabling this will break tests.
graph_sorted_nodes = []

[lints.rust]
# Spell check `#[cfg(doubly_linked_list_impl = "alt")]` etc in the code.
# Pass `--check-cfg cfg(...)` args to rustc.
unexpected_cfgs = { level = "forbid", check-cfg = [
    'cfg(doubly_linked_list_impl, values("alt", "ub", "ub_alt"))',
    ] }
