pub mod circular_buffer;
pub mod doubly_linked_list;
pub mod forth;
mod forth_alloc_attack;
pub mod luhn;
pub mod luhn_from;
pub mod luhn_trait;
pub mod macros;
pub mod macros_compile_fail_tests;
pub mod ocr_numbers;
pub mod par_letters;
pub mod react;
pub mod xorcism;
